version: "3"
services:
  tedge:
    build:
      dockerfile: alpine-s6.dockerfile
      context: "."
    restart: always
    # ports:
    #   - "1883:1883"
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
      - C8Y_USER=${C8Y_USER:-}
      - C8Y_PASSWORD=${C8Y_PASSWORD:-}
    volumes:
      - mosquitto:/mosquitto/data
      - device-certs:/etc/tedge/device-certs
    tmpfs:
      - /tmp

volumes:
  device-certs:
  mosquitto:
