# [init] system is mandatory in <= 0.8.1
[init]
name = "systemd"
is_available = ["/bin/systemctl", "--version"]
start = ["/bin/systemctl", "start", "{}"]
restart = ["/bin/systemctl", "restart", "{}"]
stop =  ["/bin/systemctl", "stop", "{}"]
enable =  ["/bin/systemctl", "enable", "{}"]
disable =  ["/bin/systemctl", "disable", "{}"]
is_active = ["/bin/systemctl", "is-active", "{}"]

[system]
reboot = ["/usr/bin/on_shutdown.sh"]
